# ~/.tmuxinator/camper.yml

name: camper
root: ~/hyrax-sample
pre_window: rvm use ruby-2.4.2
windows:
  - dev_servers:
      layout: main-vertical
      panes:
        - rails s
        - fcrepo_wrapper
        - solr_wrapper
  - code:
      layout: main-vertical
      panes:
        - echo "run vim . if you don't know what else to do"

#  - test_servers:
#      layout: main-vertical
#      panes:
#        - fcrepo_wrapper --config config/fcrepo_wrapper_test.yml
#        - rm -rf tmp/solr-test && bundle exec solr_wrapper --config config/solr_wrapper_test.yml
#  - sidekiq:
#      layout: main-vertical
#      panes:
#        - bundle exec sidekiq
